name: Data Visualizer

on:

  workflow_dispatch:

jobs:

  Run_R_Script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::ggplot2

      - name: Run R script
        run: Rscript data_analysis_R_script.R

      - name: Commit changes
        run: |
          git config --global user.name "DanielBrett"
          git config --global user.email "dbrett@brocku.ca"
          git add .
          git commit -m "Data Visualizer was activated"
          git push
